const partidos = [
  {
    club: "CF Lloret",
    temporada: "2024/25",
    jornada: "Jornada 1",
    rival: "Figueres UE",
    resultado: "2-3",
    goleadores: ["EXPÓSITO LÓPEZ ADRIAN", "LOBO FORNAS ALEX"],
    resultadoDescanso: "2-1",
    arbitro: "MONTERO CASADO ENRIC",
    escudoLocal: "https://files.fcf.cat/escudos/clubes/escudos/00100_0000981119_LOGO_CF_Lloret_Basic.png", // Escudo CF Lloret
    escudoVisitante: "https://files.fcf.cat/escudos/clubes/escudos/00100_0001086121_figueres.png", // Escudo Figueres UE
    opcionesResultado: ["1-2", "2-1", "2-3", "1-1"],
    opcionesGoleadores: [["EXPÓSITO LÓPEZ, ADRIAN", "LOBO FORNAS, ALEX"], ["Xavi"], ["Dídac"], ["Pau"]],
    opcionesArbitro: ["MONTERO CASADO, ENRIC", "Pérez González", "Martín Ruiz", "Fernández Soto"],
    local: true,
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 2",
    "rival": "SAN MAURO, U.D. A",
    "resultado": "3-0",
    "goleadores": [],
    "resultadoDescanso": "2-0",
    "arbitro": "TABIZA AHOUARY, MOHAMED",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001021772_ESCUDO_NUEVO_UD_SAN_MAURO_BUENO_camiseta_juego.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000981119_LOGO_CF_Lloret_Basic.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": false
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 3",
    "rival": "CASTELLDEFELS, U.E. A",
    "resultado": "2-2",
    "goleadores": ["BARROSO FRÍAS RUBÉN", "EXPÓSITO LÓPEZ ADRIAN"],
    "resultadoDescanso": "0-0",
    "arbitro": "GENE MORA PAU",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000981119_LOGO_CF_Lloret_Basic.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000654303_castelldefels_200x200.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    local: true
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 4",
    "rival": "ATLETIC SANT JUST. F.C. A",
    "resultado": "2-0",
    "goleadores": [],
    "resultadoDescanso": "0-0",
    "arbitro": "TABIZA AHOUARY, MOHAMED",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000572534_stjust_200x200.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000981119_LOGO_CF_Lloret_Basic.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    local: false
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 5",
    "rival": "VIC UNIÓ ESPORTIVA CLUB A",
    "resultado": "0-2",
    "goleadores": [],
    "resultadoDescanso": "0-1",
    "arbitro": "AGUIRREBEITIA MORENO, IKER",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000981119_LOGO_CF_Lloret_Basic.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000866902_uevic_200.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    local: true
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 6",
    "rival": "VALLS U.E. A",
    "resultado": "2-1",
    "goleadores": ["CHAMIZO"],
    "resultadoDescanso": "0-1",
    "arbitro": "TORRES HOYAS, ALEX",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000959056_3248_Vallsue_200.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000981119_LOGO_CF_Lloret_Basic.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    local: false
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 7",
    "rival": "RAPITENCA, U.E. A",
    "resultado": "1-2",
    "goleadores": ["SANCES IKER", "FLORES MIGUEL ANGEL"],
    "resultadoDescanso": "0-1",
    "arbitro": "TORRENT, JORDI",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000739646_rapitenca_200x200.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000981119_LOGO_CF_Lloret_Basic.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    local: false
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 8",
    "rival": "PALAMOS CLUB DE FUTBOL A",
    "resultado": "1-2",
    "goleadores": ["MAICOHOL EVIA"],
    "resultadoDescanso": "1-1",
    "arbitro": "MURILLO FIOL, RODRIGO",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000981119_LOGO_CF_Lloret_Basic.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000654696_palamos_200x200.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    local: true
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 9",
    "rival": "MANLLEU, A.E.C. A",
    "resultado": "3-1",
    "goleadores": ["ALEJANDRO FERNANDEZ"],
    "resultadoDescanso": "0-1",
    "arbitro": "TORRENT, JORDI",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001085506_Escut_AEC_Manlleu.jpg",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000981119_LOGO_CF_Lloret_Basic.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    local: false
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 10",
    "rival": "VILANOVA GELTRU C.F. A",
    "resultado": "2-4",
    "goleadores": ["IKER SANCES"],
    "resultadoDescanso": "1-2",
    "arbitro": "MURILLO FIOL, RODRIGO",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000981119_LOGO_CF_Lloret_Basic.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001044079_cfv.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 12",
    "rival": "GRANOLLERS, E.C. A",
    "resultado": "3-1",
    "resultadoDescanso": "2-0",
    "goleadores": ["MARC", "VITOR", "ROGER (P.P.)"],
    "arbitro": "BORONAT LLANO, MARC",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001106092_escudo1.jpg",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": true
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 13",
    "rival": "MOLLET U.E, CF. A",
    "resultado": "2-1",
    "resultadoDescanso": "1-1",
    "goleadores": ["MAYCOL"],
    "arbitro": "ITURBE SAINZ DE LA MAZA, MARTI",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001057534_escut4.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": false
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 14",
    "rival": "MONTCADA, C.D A",
    "resultado": "2-1",
    "resultadoDescanso": "1-1",
    "goleadores": ["MAMADOU", "GONZALO"],
    "arbitro": "RIVERA LOPEZ, RAUL",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000427544_MONTCADA.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": true
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 15",
    "rival": "ROSES, A.E. A",
    "resultado": "2-5",
    "resultadoDescanso": "1-4",
    "goleadores": ["DAMIAN (2)", "ILIR (2)", "JUAN CRUZ"],
    "arbitro": "ROJAS CALVERA, ALEIX",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000816719_aer_200.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": false
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 16",
    "rival": "TORELLO, C.F. A",
    "resultado": "3-1",
    "resultadoDescanso": "1-1",
    "goleadores": ["ILIR"],
    "arbitro": "RIVERA BRAVO, FRANCISCO JOSE",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000651415_torello_200x200.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": false
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 17",
    "rival": "CASTELLAR, UNIO ESPORTIVA A",
    "resultado": "4-2",
    "resultadoDescanso": "3-1",
    "goleadores": ["LUCHO", "ILIR (2)", "LUCAS"],
    "arbitro": "KAHOUACH BELHAJ, MONIM",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000259441_CASTELLAR_UE.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": true
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 18",
    "rival": "BANYOLES, C.E. A",
    "resultado": "0-0",
    "resultadoDescanso": "0-0",
    "goleadores": [],
    "arbitro": "PLUMA ROVIRA, ROGER",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000651540_cebanyoles_200x200.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": false
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 19",
    "rival": "CALDES MONTBUI, C.F. A",
    "resultado": "0-3",
    "resultadoDescanso": "0-2",
    "goleadores": [],
    "arbitro": "LOPEZ BRUSTENGA, IRENE",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000009672_Caldes%20escut.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": true
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 20",
    "rival": "TOSSA UNIO ESPORTIVA A",
    "resultado": "1-0",
    "resultadoDescanso": "1-0",
    "goleadores": ["ILIR"],
    "arbitro": "AJEOB KHOMSI, HAMZA",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000574541_tossa_200x200.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": true
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 21",
    "rival": "CAN GIBERT, U.E A",
    "resultado": "2-2",
    "resultadoDescanso": "2-1",
    "goleadores": ["KEVIN", "DAMIAN"],
    "arbitro": "MURILLO FIOL, RODRIGO",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000003420_Unio%20Esportiva%20Can%20Gibert.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": false
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 22",
    "rival": "PARETS, C.F. A",
    "resultado": "3-0",
    "resultadoDescanso": "2-0",
    "goleadores": ["GONZALO", "MARC", "GONZALO"],
    "arbitro": "ESSELILAM, YOUSSEF",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001030385_1123_200.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": true
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 23",
    "rival": "SAN JUAN AT. DE MONTCADA, U.E. A",
    "resultado": "3-0",
    "resultadoDescanso": "2-0",
    "goleadores": [],
    "arbitro": "RAMOS MUÑOZ, IVAN",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000275028_logoUnion.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": false
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 24",
    "rival": "TORROELLA, U.E. A",
    "resultado": "2-2",
    "resultadoDescanso": "1-1",
    "goleadores": ["GONZALO", "LUCHO"],
    "arbitro": "FERNANDEZ VILA, TETYANA",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000822232_torroella_200.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": true
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 25",
    "rival": "ARGENTONA, C.F. A",
    "resultado": "0-1",
    "resultadoDescanso": "0-1",
    "goleadores": ["KEVIN"],
    "arbitro": "BARNILS DELGADO, PAU",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000886895_fcargentona_200.png",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": false
  },
  {
    "club": "JUVENTUS-LLORET",
    "temporada": "2024/25",
    "jornada": "Jornada 26",
    "rival": "BESCANO, C.D. A",
    "resultado": "3-3",
    "resultadoDescanso": "1-1",
    "goleadores": ["LUCHO", "ILIR", "LUCHO"],
    "arbitro": "NAVARRO GOMEZ, GERMAN",
    "escudoLocal": "https://files.fcf.cat/escudos/clubes/escudos/00100_0001022362_Screenshot_2024_07_02_17_11_59_443_com.whatsapp_edit.jpg",
    "escudoVisitante": "https://files.fcf.cat/escudos/clubes/escudos/00100_0000739644_bescano_200x200.png",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": [],
    "local": true
  }

];

export default partidos;