const partidos = [
  {
    club: "CF Lloret",
    temporada: "2024/25",
    jornada: "Jornada 1",
    rival: "Figueres UE",
    resultado: "2-3",
    goleadores: ["EXPÓSITO LÓPEZ, ADRIAN", "LOBO FORNAS, ALEX"],
    resultadoDescanso: "2-1",
    arbitro: "MONTERO CASADO, ENRIC",
    escudoLocal: "https://files.fcf.cat/escudos/clubes/escudos/00100_0000981119_LOGO_CF_Lloret_Basic.png", // Escudo CF Lloret
    escudoVisitante: "https://files.fcf.cat/escudos/clubes/escudos/00100_0001086121_figueres.png", // Escudo Figueres UE
    opcionesResultado: ["1-2", "2-1", "2-3", "1-1"],
    opcionesGoleadores: [["EXPÓSITO LÓPEZ, ADRIAN", "LOBO FORNAS, ALEX"], ["Xavi"], ["Dídac"], ["Pau"]],
    opcionesArbitro: ["MONTERO CASADO, ENRIC", "Pérez González", "Martín Ruiz", "Fernández Soto"]
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 2",
    "rival": "SAN MAURO, U.D. A",
    "resultado": "3-0",
    "goleadores": [],
    "resultadoDescanso": "2-0",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 3",
    "rival": "CASTELLDEFELS, U.E. A",
    "resultado": "2-2",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "⚽",
    "escudoVisitante": "🔴",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 4",
    "rival": "ATLETIC SANT JUST. F.C. A",
    "resultado": "2-0",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 5",
    "rival": "VIC UNIÓ ESPORTIVA CLUB A",
    "resultado": "0-2",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "⚽",
    "escudoVisitante": "🔴",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 6",
    "rival": "VALLS U.E. A",
    "resultado": "2-1",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 7",
    "rival": "RAPITENCA, U.E. A",
    "resultado": "1-3",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 8",
    "rival": "PALAMOS CLUB DE FUTBOL A",
    "resultado": "1-2",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "⚽",
    "escudoVisitante": "🔴",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 9",
    "rival": "MANLLEU, A.E.C. A",
    "resultado": "3-1",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 10",
    "rival": "VILANOVA GELTRU C.F. A",
    "resultado": "2-4",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "⚽",
    "escudoVisitante": "🔴",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 11",
    "rival": "POBLA MAFUMET, C.F. A",
    "resultado": "3-2",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 12",
    "rival": "VILAFRANCA, F.C. A",
    "resultado": "1-0",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "⚽",
    "escudoVisitante": "🔴",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 13",
    "rival": "HORTA, U.A.T. A",
    "resultado": "3-1",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 14",
    "rival": "RUBI, U.E. A",
    "resultado": "3-3",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "⚽",
    "escudoVisitante": "🔴",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 15",
    "rival": "CAN VIDALET, C.F. A",
    "resultado": "3-1",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 16",
    "rival": "FIGUERES, U.E. A",
    "resultado": "0-2",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 17",
    "rival": "SAN MAURO, U.D. A",
    "resultado": "2-0",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "⚽",
    "escudoVisitante": "🔴",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 18",
    "rival": "CASTELLDEFELS, U.E. A",
    "resultado": "1-0",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 19",
    "rival": "ATLETIC SANT JUST. F.C. A",
    "resultado": "2-4",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "⚽",
    "escudoVisitante": "🔴",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 20",
    "rival": "VIC UNIÓ ESPORTIVA CLUB A",
    "resultado": "3-1",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 21",
    "rival": "VALLS U.E. A",
    "resultado": "0-2",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "⚽",
    "escudoVisitante": "🔴",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 22",
    "rival": "RAPITENCA, U.E. A",
    "resultado": "2-1",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "⚽",
    "escudoVisitante": "🔴",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 23",
    "rival": "PALAMOS CLUB DE FUTBOL A",
    "resultado": "3-1",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 24",
    "rival": "MANLLEU, A.E.C. A",
    "resultado": "1-2",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "⚽",
    "escudoVisitante": "🔴",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  },
  {
    "club": "CF Lloret",
    "temporada": "2024/25",
    "jornada": "Jornada 25",
    "rival": "VILANOVA GELTRU C.F. A",
    "resultado": "2-1",
    "goleadores": [],
    "resultadoDescanso": "",
    "arbitro": "",
    "escudoLocal": "🔴",
    "escudoVisitante": "⚽",
    "opcionesResultado": [],
    "opcionesGoleadores": [],
    "opcionesArbitro": []
  }
];

export default partidos;